/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationDesign;

import Classes.BookingArray;
import Classes.CommunityArray;
import Classes.EncounterArray;
import Classes.HospitalArray;
import Classes.Person;
import Classes.PersonArray;
import CommunityAdmins.ComAdminMainFrame;
import Doctor.DoctorMainFrame;
import HospitalAdmin.HospitalAdminsMainFrame;
import Patient.PatientMainFrame;
import SystemAdmin.SysAdmMainFrame;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vishwashah
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
     public static LogIn Instance;
    public JTextField tmpLogInUsernameInput;
    public static final String SYSUSERNAME = "vishwa";
    public static final String SYSPASS = "1234@";

    /**
     * Creates new form LogIn
     */
    
    PersonArray person;
    HospitalArray hospital;
    CommunityArray community;
    BookingArray booking;
    EncounterArray encounter;
    
    public LogIn(PersonArray person, HospitalArray hospital, CommunityArray community, BookingArray booking, EncounterArray encounter) {
        initComponents();
        Instance = this;
        tmpLogInUsernameInput = LogInUsernameInput;
        
        this.person = person;
        this.hospital = hospital;
        this.community = community;
        this.booking = booking;
        this.encounter = encounter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        LogIn = new javax.swing.JLabel();
        LogInUsernameLbl = new javax.swing.JLabel();
        LogInPasswordLbl = new javax.swing.JLabel();
        LogInTypeLbl = new javax.swing.JLabel();
        LogInUsernameInput = new javax.swing.JTextField();
        LogInTypeInput = new javax.swing.JComboBox<>();
        LogInButton = new javax.swing.JButton();
        LogInUsernameErrMsg = new javax.swing.JLabel();
        LogInPassErrMsg = new javax.swing.JLabel();
        LogInPasswordInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        LogIn.setFont(new java.awt.Font("KufiStandardGK", 1, 18)); // NOI18N
        LogIn.setForeground(new java.awt.Color(51, 51, 51));
        LogIn.setText("LOG IN PAGE");

        LogInUsernameLbl.setBackground(new java.awt.Color(255, 255, 255));
        LogInUsernameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogInUsernameLbl.setForeground(new java.awt.Color(51, 51, 51));
        LogInUsernameLbl.setText("Username:");
        LogInUsernameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LogInPasswordLbl.setBackground(new java.awt.Color(255, 255, 255));
        LogInPasswordLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogInPasswordLbl.setForeground(new java.awt.Color(51, 51, 51));
        LogInPasswordLbl.setText("Password:");
        LogInPasswordLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LogInTypeLbl.setBackground(new java.awt.Color(255, 255, 255));
        LogInTypeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogInTypeLbl.setForeground(new java.awt.Color(51, 51, 51));
        LogInTypeLbl.setText("Type:");
        LogInTypeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LogInUsernameInput.setBackground(new java.awt.Color(238, 238, 238));
        LogInUsernameInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        LogInUsernameInput.setForeground(new java.awt.Color(51, 51, 51));
        LogInUsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInUsernameInputActionPerformed(evt);
            }
        });
        LogInUsernameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LogInUsernameInputKeyReleased(evt);
            }
        });

        LogInTypeInput.setBackground(new java.awt.Color(238, 238, 238));
        LogInTypeInput.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        LogInTypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "System Admin", "Patient", "Doctor", "Community Admin", "Hospital Admin" }));
        LogInTypeInput.setPreferredSize(new java.awt.Dimension(64, 23));
        LogInTypeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInTypeInputActionPerformed(evt);
            }
        });

        LogInButton.setBackground(new java.awt.Color(0, 153, 153));
        LogInButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(255, 255, 255));
        LogInButton.setText("Log In");
        LogInButton.setMaximumSize(new java.awt.Dimension(120, 50));
        LogInButton.setMinimumSize(new java.awt.Dimension(120, 50));
        LogInButton.setPreferredSize(new java.awt.Dimension(200, 60));
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });

        LogInUsernameErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        LogInUsernameErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LogInUsernameErrMsg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        LogInUsernameErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LogInPassErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        LogInPassErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LogInPassErrMsg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        LogInPassErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LogInPasswordInput.setBackground(new java.awt.Color(238, 238, 238));
        LogInPasswordInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        LogInPasswordInput.setForeground(new java.awt.Color(51, 51, 51));
        LogInPasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInPasswordInputActionPerformed(evt);
            }
        });
        LogInPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LogInPasswordInputKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(LogInTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LogInTypeLbl)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LogInUsernameLbl)
                                .addComponent(LogInPasswordLbl))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LogInUsernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(LogInUsernameErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LogInPassErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LogInPasswordInput)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogInTypeLbl))
                .addGap(41, 41, 41)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInUsernameLbl)
                    .addComponent(LogInUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(LogInUsernameErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInPasswordLbl)
                    .addComponent(LogInPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogInPassErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInUsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInUsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInUsernameInputActionPerformed

    private void LogInUsernameInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogInUsernameInputKeyReleased
        // TODO add your handling code here:
        int count = 0;
        String type = (String) LogInTypeInput.getSelectedItem();
        for(Person p:person.getPerson()) {
            String test = p.getPersonType();
            if(test.equals(type)) {
                count++;
            }
        }
        if(count > 0) {
            LogInUsernameErrMsg.setText(null);
        } else if(type.equals(SYSUSERNAME)) {
            LogInUsernameErrMsg.setText(null);
        } else {
            LogInUsernameErrMsg.setText("Please enter valid Username");
        }
    }//GEN-LAST:event_LogInUsernameInputKeyReleased

    private void LogInTypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInTypeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInTypeInputActionPerformed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        // TODO add your handling code here:
         String username = LogInUsernameInput.getText();
        String pass = LogInPasswordInput.getText();
        String type = LogInTypeInput.getSelectedItem().toString();
                
        if(username.equals(SYSUSERNAME) && pass.equals(SYSPASS) && type.equals("System Admin")) {
            this.dispose();
            AdminFrame.Instance.tmpLogInText.setText("Log in into another account?");
            AdminFrame.Instance.tmpLogInButton.setText("Log Out");
            
            SysAdmMainFrame systemAdminAddPerson = new SysAdmMainFrame(person, hospital, community, booking, encounter);
            AdminFrame.Instance.tmpMainSplit.setBottomComponent(systemAdminAddPerson);
            
        } else {
            int count = 0;
            for(Person p:person.getPerson()) {
                String testUsername = p.getPersonEmail();
                String testPass = p.getPass();
                String testType = p.getPersonType();
                if(testUsername.equals(username) && testPass.equals(pass) && testType.equals(type)) {
                    count++;
                }
            }
            if(count == 1) {
                this.dispose();
                AdminFrame.Instance.tmpLogInText.setText("Log in into another account?");
                AdminFrame.Instance.tmpLogInButton.setText("Log Out");
                
                switch (type) {
                    case "Patient" -> {
                        PatientMainFrame patientMainFrame = new PatientMainFrame(person, hospital, community, booking, encounter);
                        AdminFrame.Instance.tmpMainSplit.setBottomComponent(patientMainFrame);
                    }
                    case "Doctor" -> {
                        DoctorMainFrame doctorMainFrame = new DoctorMainFrame(person, hospital, community, booking, encounter);
                        AdminFrame.Instance.tmpMainSplit.setBottomComponent(doctorMainFrame);
                    }
                    case "Community Admin" -> {
                        ComAdminMainFrame comAdminMainFrame = new ComAdminMainFrame(person, hospital, community, booking, encounter);
                        AdminFrame.Instance.tmpMainSplit.setBottomComponent(comAdminMainFrame);
                    }
                    case "Hospital Admin" -> {
                        HospitalAdminsMainFrame hospitalAdminsMainFrame = new HospitalAdminsMainFrame(person, hospital, community, booking, encounter);
                        AdminFrame.Instance.tmpMainSplit.setBottomComponent(hospitalAdminsMainFrame);
                    }
                    default -> {
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this,"Entered details does not match with records");
            }
        }
    }//GEN-LAST:event_LogInButtonActionPerformed

    private void LogInPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInPasswordInputActionPerformed

    private void LogInPasswordInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogInPasswordInputKeyReleased
        // TODO add your handling code here:
        String validation="^[a-zA-Z0-9]{11}";
        Pattern test = Pattern.compile(validation);
        Matcher ontest = test.matcher(LogInPasswordInput.getText());
        if(!ontest.matches() || LogInPasswordInput.getText().equals(SYSPASS)){
            LogInPassErrMsg.setText("Password lengh must be 11");
        }
        else {
            LogInPassErrMsg.setText(null);
        }
    }//GEN-LAST:event_LogInPasswordInputKeyReleased

//////    /**
//////     * @param args the command line arguments
//////     */
//    public static void main(String args[]) {
//////        /* Set the Nimbus look and feel */
//////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//////         */
//////        try {
//////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//////                if ("Nimbus".equals(info.getName())) {
//////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//////                    break;
//////                }
//////            }
//////        } catch (ClassNotFoundException ex) {
//////            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        } catch (InstantiationException ex) {
//////            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        } catch (IllegalAccessException ex) {
//////            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//////            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        }
//////        //</editor-fold>
//////
//////        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//           public void run() {
//               new LogIn(person, hospital, community, booking, encounter).setVisible(true);
//            }
//       });
//   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogIn;
    private javax.swing.JButton LogInButton;
    private javax.swing.JLabel LogInPassErrMsg;
    private javax.swing.JTextField LogInPasswordInput;
    private javax.swing.JLabel LogInPasswordLbl;
    private javax.swing.JComboBox<String> LogInTypeInput;
    private javax.swing.JLabel LogInTypeLbl;
    private javax.swing.JLabel LogInUsernameErrMsg;
    private javax.swing.JTextField LogInUsernameInput;
    private javax.swing.JLabel LogInUsernameLbl;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
