/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemAdmin;

import Classes.BookingArray;
import Classes.Community;
import Classes.CommunityArray;
import Classes.EncounterArray;
import Classes.HospitalArray;
import Classes.Person;
import Classes.PersonArray;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author vishwashah
 */
public class AddPerson extends javax.swing.JPanel {

    /**
     * Creates new form AddPerson
     */
    PersonArray person;
    HospitalArray hospital;
    CommunityArray community;
    BookingArray booking;
    EncounterArray encounter;
    
    public AddPerson(PersonArray person, HospitalArray hospital, CommunityArray community, BookingArray booking, EncounterArray encounter) {
        initComponents();
        
        this.person = person;
        this.hospital = hospital;
        this.community = community;
        this.booking = booking;
        this.encounter = encounter;
        
        addCommuniy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TypeLbl = new javax.swing.JLabel();
        TypeInput = new javax.swing.JComboBox<>();
        NameLbl = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        IdLbl = new javax.swing.JLabel();
        IdInput = new javax.swing.JTextField();
        AgeLbl = new javax.swing.JLabel();
        AgeInput = new javax.swing.JSpinner();
        GenderLbl = new javax.swing.JLabel();
        FemaleRadio = new javax.swing.JRadioButton();
        MaleRadio = new javax.swing.JRadioButton();
        OtherRadio = new javax.swing.JRadioButton();
        ContactLbl = new javax.swing.JLabel();
        ContactInput = new javax.swing.JTextField();
        EmailLbl = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        CommunityLbl = new javax.swing.JLabel();
        CommunityInput = new javax.swing.JComboBox<>();
        CityLbl = new javax.swing.JLabel();
        CityInput = new javax.swing.JTextField();
        HouseNoLbl = new javax.swing.JLabel();
        HouseNoInput = new javax.swing.JTextField();
        StreetLbl = new javax.swing.JLabel();
        StreetInput = new javax.swing.JTextField();
        PassLbl = new javax.swing.JLabel();
        PassInput = new javax.swing.JTextField();
        ConfPasslbl = new javax.swing.JLabel();
        ConfPassInput = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        IdErrMsg = new javax.swing.JLabel();
        ContactErrMsg = new javax.swing.JLabel();
        EmailErrMsg = new javax.swing.JLabel();
        PassErrMsg = new javax.swing.JLabel();
        ConfPassErrMsg = new javax.swing.JLabel();
        PassErrMsg1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TypeLbl.setBackground(new java.awt.Color(255, 255, 255));
        TypeLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        TypeLbl.setText("Type:");
        TypeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        TypeInput.setBackground(new java.awt.Color(238, 238, 238));
        TypeInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Person", "Patient", "Doctor", "Community Admin", "Hospital Admin" }));
        TypeInput.setPreferredSize(new java.awt.Dimension(64, 23));
        TypeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeInputActionPerformed(evt);
            }
        });

        NameLbl.setBackground(new java.awt.Color(255, 255, 255));
        NameLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        NameLbl.setText("Name:");
        NameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        NameInput.setBackground(new java.awt.Color(238, 238, 238));
        NameInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        NameInput.setForeground(new java.awt.Color(51, 51, 51));
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        IdLbl.setBackground(new java.awt.Color(255, 255, 255));
        IdLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        IdLbl.setText("ID:");
        IdLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        IdInput.setBackground(new java.awt.Color(238, 238, 238));
        IdInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        IdInput.setForeground(new java.awt.Color(51, 51, 51));
        IdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdInputActionPerformed(evt);
            }
        });
        IdInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdInputKeyReleased(evt);
            }
        });

        AgeLbl.setBackground(new java.awt.Color(255, 255, 255));
        AgeLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        AgeLbl.setText("Age:");
        AgeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        AgeInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        AgeInput.setModel(new javax.swing.SpinnerNumberModel(22, 18, 62, 1));

        GenderLbl.setBackground(new java.awt.Color(255, 255, 255));
        GenderLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        GenderLbl.setText("Gender:");
        GenderLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        FemaleRadio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        FemaleRadio.setForeground(new java.awt.Color(51, 51, 51));
        FemaleRadio.setText("Female");

        MaleRadio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        MaleRadio.setForeground(new java.awt.Color(51, 51, 51));
        MaleRadio.setText("Male");
        MaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioActionPerformed(evt);
            }
        });

        OtherRadio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        OtherRadio.setForeground(new java.awt.Color(51, 51, 51));
        OtherRadio.setText("Other");
        OtherRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherRadioActionPerformed(evt);
            }
        });

        ContactLbl.setBackground(new java.awt.Color(255, 255, 255));
        ContactLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        ContactLbl.setText("Contact:");
        ContactLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ContactInput.setBackground(new java.awt.Color(238, 238, 238));
        ContactInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactInput.setForeground(new java.awt.Color(51, 51, 51));
        ContactInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactInputActionPerformed(evt);
            }
        });
        ContactInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContactInputKeyReleased(evt);
            }
        });

        EmailLbl.setBackground(new java.awt.Color(255, 255, 255));
        EmailLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        EmailLbl.setText("Email:");
        EmailLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        EmailInput.setBackground(new java.awt.Color(238, 238, 238));
        EmailInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        EmailInput.setForeground(new java.awt.Color(51, 51, 51));
        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });
        EmailInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailInputKeyReleased(evt);
            }
        });

        CommunityLbl.setBackground(new java.awt.Color(255, 255, 255));
        CommunityLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        CommunityLbl.setText("Community:");
        CommunityLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        CommunityInput.setBackground(new java.awt.Color(238, 238, 238));
        CommunityInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CommunityInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Community" }));
        CommunityInput.setPreferredSize(new java.awt.Dimension(64, 23));
        CommunityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityInputActionPerformed(evt);
            }
        });

        CityLbl.setBackground(new java.awt.Color(255, 255, 255));
        CityLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        CityLbl.setText("City:");
        CityLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        CityInput.setBackground(new java.awt.Color(238, 238, 238));
        CityInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CityInput.setForeground(new java.awt.Color(51, 51, 51));
        CityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityInputActionPerformed(evt);
            }
        });

        HouseNoLbl.setBackground(new java.awt.Color(255, 255, 255));
        HouseNoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HouseNoLbl.setText("House No:");
        HouseNoLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        HouseNoInput.setBackground(new java.awt.Color(238, 238, 238));
        HouseNoInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        HouseNoInput.setForeground(new java.awt.Color(51, 51, 51));
        HouseNoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseNoInputActionPerformed(evt);
            }
        });

        StreetLbl.setBackground(new java.awt.Color(255, 255, 255));
        StreetLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        StreetLbl.setText("Street:");
        StreetLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        StreetInput.setBackground(new java.awt.Color(238, 238, 238));
        StreetInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        StreetInput.setForeground(new java.awt.Color(51, 51, 51));
        StreetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetInputActionPerformed(evt);
            }
        });

        PassLbl.setBackground(new java.awt.Color(255, 255, 255));
        PassLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        PassLbl.setText("Password:");
        PassLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        PassInput.setBackground(new java.awt.Color(238, 238, 238));
        PassInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        PassInput.setForeground(new java.awt.Color(51, 51, 51));
        PassInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassInputActionPerformed(evt);
            }
        });
        PassInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PassInputKeyReleased(evt);
            }
        });

        ConfPasslbl.setBackground(new java.awt.Color(255, 255, 255));
        ConfPasslbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        ConfPasslbl.setText("Confirm Password:");
        ConfPasslbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ConfPassInput.setBackground(new java.awt.Color(238, 238, 238));
        ConfPassInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ConfPassInput.setForeground(new java.awt.Color(51, 51, 51));
        ConfPassInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfPassInputActionPerformed(evt);
            }
        });
        ConfPassInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ConfPassInputKeyReleased(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(0, 153, 153));
        AddButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("ADD");
        AddButton.setMaximumSize(new java.awt.Dimension(120, 50));
        AddButton.setMinimumSize(new java.awt.Dimension(120, 50));
        AddButton.setPreferredSize(new java.awt.Dimension(200, 60));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        IdErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        IdErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        IdErrMsg.setForeground(new java.awt.Color(255, 51, 51));
        IdErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ContactErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        ContactErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ContactErrMsg.setForeground(new java.awt.Color(255, 51, 51));
        ContactErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        EmailErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        EmailErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        EmailErrMsg.setForeground(new java.awt.Color(255, 51, 51));
        EmailErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        PassErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        PassErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PassErrMsg.setForeground(new java.awt.Color(255, 51, 51));
        PassErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ConfPassErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        ConfPassErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ConfPassErrMsg.setForeground(new java.awt.Color(255, 51, 51));
        ConfPassErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        PassErrMsg1.setBackground(new java.awt.Color(255, 255, 255));
        PassErrMsg1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PassErrMsg1.setForeground(new java.awt.Color(255, 51, 51));
        PassErrMsg1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLbl)
                            .addComponent(TypeLbl)
                            .addComponent(IdLbl)
                            .addComponent(GenderLbl)
                            .addComponent(ContactLbl)
                            .addComponent(CommunityLbl)
                            .addComponent(CityLbl)
                            .addComponent(StreetLbl)
                            .addComponent(EmailLbl)
                            .addComponent(ConfPasslbl))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FemaleRadio)
                                .addGap(18, 18, 18)
                                .addComponent(MaleRadio)
                                .addGap(18, 18, 18)
                                .addComponent(OtherRadio))
                            .addComponent(TypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(AgeLbl)
                                .addGap(10, 10, 10)
                                .addComponent(AgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CommunityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(HouseNoLbl)
                                .addGap(10, 10, 10)
                                .addComponent(HouseNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ContactInput)
                            .addComponent(StreetInput)
                            .addComponent(NameInput)
                            .addComponent(EmailInput)
                            .addComponent(PassInput)
                            .addComponent(ConfPassInput, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(PassLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(EmailErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PassErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConfPassErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(IdErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(459, 459, 459)
                    .addComponent(PassErrMsg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLbl)
                    .addComponent(TypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLbl)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLbl)
                    .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeLbl)
                    .addComponent(AgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FemaleRadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GenderLbl)
                        .addComponent(MaleRadio)
                        .addComponent(OtherRadio)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ContactLbl)
                        .addComponent(ContactInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLbl)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommunityLbl)
                    .addComponent(CommunityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLbl)
                    .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HouseNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HouseNoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetLbl)
                    .addComponent(StreetInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PassLbl)
                        .addComponent(PassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfPasslbl)
                    .addComponent(ConfPassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfPassErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(448, 448, 448)
                    .addComponent(PassErrMsg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(325, 325, 325)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeInputActionPerformed

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void IdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdInputActionPerformed

    private void IdInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdInputKeyReleased
        // TODO add your handling code here:
        int count = 0;
        for(Person p:person.getPerson()) {
            int test = p.getPersonID();
            int ontest = Integer.parseInt(IdInput.getText());
            if(test == ontest) {
                count++;
            }
        }
        if(count > 0) {
            IdErrMsg.setText("Enter Uniue Id");
        } else {
            IdErrMsg.setText(null);
        }
    }//GEN-LAST:event_IdInputKeyReleased

    private void MaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioActionPerformed

    private void OtherRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtherRadioActionPerformed

    private void ContactInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactInputActionPerformed

    private void ContactInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactInputKeyReleased
        // TODO add your handling code here:
        String validation = "^[0-9]{10}";
        Pattern test = Pattern.compile(validation);
        Matcher ontest = test.matcher(ContactInput.getText());
        if(!ontest.matches()){
            ContactErrMsg.setText("Enter 10 digits number");
        }
        else {
            ContactErrMsg.setText(null);
        }
    }//GEN-LAST:event_ContactInputKeyReleased

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void EmailInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailInputKeyReleased
        // TODO add your handling code here:
         String validation="^(?=.{1,81}$)[\\w\\.-]+@koku\\.org";
        Pattern test = Pattern.compile(validation);
        Matcher ontest = test.matcher(EmailInput.getText());
        if(!ontest.matches()){
            EmailErrMsg.setText("Enter correct email");
        }
        else {
            EmailErrMsg.setText(null);
        }
    }//GEN-LAST:event_EmailInputKeyReleased

    private void CommunityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityInputActionPerformed
        // TODO add your handling code here:
        String tempCom = (String) CommunityInput.getSelectedItem();
        
        for(Community c:community.getCommunity()) {
            String check = c.getCommunityName();
            if(check.equals(tempCom)) {
                CityInput.setText(c.getCommunityCity());
            }
        }
    }//GEN-LAST:event_CommunityInputActionPerformed

    private void CityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityInputActionPerformed

    private void HouseNoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseNoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HouseNoInputActionPerformed

    private void StreetInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetInputActionPerformed

    private void PassInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassInputActionPerformed

    private void PassInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassInputKeyReleased
        // TODO add your handling code here:
       String validation="^[a-zA-Z0-9]{11}";
        Pattern test = Pattern.compile(validation);
        Matcher ontest = test.matcher(PassInput.getText());
        if(!ontest.matches()){
            PassErrMsg.setText("Password lengh must be 11");
        }
        else {
            PassErrMsg.setText(null);
        }
    }//GEN-LAST:event_PassInputKeyReleased

    private void ConfPassInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfPassInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfPassInputActionPerformed

    private void ConfPassInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConfPassInputKeyReleased
        // TODO add your handling code here:
      String test = PassInput.getText();
        String ontest = ConfPassInput.getText();
        if(!ontest.equals(test)){
            ConfPassErrMsg.setText("Password dose not match");
        }
        else {
            ConfPassErrMsg.setText(null);
        }
    }//GEN-LAST:event_ConfPassInputKeyReleased

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(ContactErrMsg.getText());
        try {
            if (IdInput.getText().isEmpty() || NameInput.getText().isEmpty() ||
                    ContactInput.getText().isEmpty() || EmailInput.getText().isEmpty() ||
                    CityInput.getText().isEmpty() || HouseNoInput.getText().isEmpty() ||
                    StreetInput.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,"Please fill all data");
                
            } else if (IdErrMsg.getText() != null || ContactErrMsg.getText() != null ||
                    EmailErrMsg.getText() != null || PassErrMsg.getText() != null ||
                    ConfPassErrMsg.getText() != null) {
                JOptionPane.showMessageDialog(this,"Please fill correct data");
                
            } else {
                String personGender;
                if(FemaleRadio.isSelected()) { personGender = "Female"; }
                else if(MaleRadio.isSelected()) { personGender = "Male"; }
                else { personGender = "Other"; }

                long personContact = Long.parseLong(ContactInput.getText());

                Person p = person.addNewPerson();

                p.setPersonType((String) TypeInput.getSelectedItem());
                p.setPersonID(Integer.parseInt(IdInput.getText()));
                p.setPersonName(NameInput.getText());
                p.setPersonGender(personGender);
                p.setPersonAge((int) AgeInput.getValue());
                p.setPersonContact(personContact);
                p.setPersonEmail(EmailInput.getText());
                p.setCommunity((String) CommunityInput.getSelectedItem());
                p.setCity(CityInput.getText());
                p.setHouseNo(Integer.parseInt(HouseNoInput.getText()));
                p.setStreet(StreetInput.getText());

                NameInput.setText(null);
                IdInput.setText(null);
                ContactInput.setText(null);
                EmailInput.setText(null);
                CityInput.setText(null);
                HouseNoInput.setText(null);
                StreetInput.setText(null);

                JOptionPane.showMessageDialog(this,"Record Added");
            }
        } catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please Enter Data");
        }
    
    }//GEN-LAST:event_AddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JSpinner AgeInput;
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField CityInput;
    private javax.swing.JLabel CityLbl;
    private javax.swing.JComboBox<String> CommunityInput;
    private javax.swing.JLabel CommunityLbl;
    private javax.swing.JLabel ConfPassErrMsg;
    private javax.swing.JTextField ConfPassInput;
    private javax.swing.JLabel ConfPasslbl;
    private javax.swing.JLabel ContactErrMsg;
    private javax.swing.JTextField ContactInput;
    private javax.swing.JLabel ContactLbl;
    private javax.swing.JLabel EmailErrMsg;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JTextField HouseNoInput;
    private javax.swing.JLabel HouseNoLbl;
    private javax.swing.JLabel IdErrMsg;
    private javax.swing.JTextField IdInput;
    private javax.swing.JLabel IdLbl;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JRadioButton OtherRadio;
    private javax.swing.JLabel PassErrMsg;
    private javax.swing.JLabel PassErrMsg1;
    private javax.swing.JTextField PassInput;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JTextField StreetInput;
    private javax.swing.JLabel StreetLbl;
    private javax.swing.JComboBox<String> TypeInput;
    private javax.swing.JLabel TypeLbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 private void addCommuniy() {
        String filePath = "/Users/vishwashah/Downloads/Assignment2/files/Community.csv";
        CityInput.setEnabled(false);
        try (Scanner sc = new Scanner(new File(filePath))) {
            sc.useDelimiter("[,\n]");
            String[] temp = new String[3];
            while (sc.hasNext()) {
                for(int i = 0; i < temp.length; i++) {
                    temp[i] = sc.next();
                }
                CommunityInput.addItem(temp[0]);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonDirectory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }}
