/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemAdmin;

import Classes.BookingArray;
import Classes.CommunityArray;
import Classes.EncounterArray;
import Classes.HospitalArray;
import Classes.PersonArray;

/**
 *
 * @author vishwashah
 */
public class SysAdmMainFrame extends javax.swing.JPanel {

    /**
     * Creates new form SysAdmMainFrame
     */
      PersonArray person;
    HospitalArray hospital;
    CommunityArray community;
    BookingArray booking;
    EncounterArray encounter;
    
    public SysAdmMainFrame(PersonArray person, HospitalArray hospital, CommunityArray community, BookingArray booking, EncounterArray encounter) {
        initComponents();
        
        this.person = person;
        this.hospital = hospital;
        this.community = community;
        this.booking = booking;
        this.encounter = encounter;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WorkAreaSplit = new javax.swing.JSplitPane();
        ButtonsArea = new javax.swing.JPanel();
        AddPersonButton = new javax.swing.JButton();
        PersonDirectoryButton = new javax.swing.JButton();
        PatientDirectoryButton = new javax.swing.JButton();
        DoctorDirectoryButton = new javax.swing.JButton();
        HospitalAdminsButton = new javax.swing.JButton();
        CommunityAdminsButton = new javax.swing.JButton();
        ActionsArea = new javax.swing.JPanel();
        TypeLbl = new javax.swing.JLabel();
        TypeInput = new javax.swing.JComboBox<>();
        NameLbl = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        IdLbl = new javax.swing.JLabel();
        IdInput = new javax.swing.JTextField();
        AgeLbl = new javax.swing.JLabel();
        AgeInput = new javax.swing.JSpinner();
        GenderLbl = new javax.swing.JLabel();
        FemaleRadio = new javax.swing.JRadioButton();
        MaleRadio = new javax.swing.JRadioButton();
        OtherRadio = new javax.swing.JRadioButton();
        ContactLbl = new javax.swing.JLabel();
        ContactInput = new javax.swing.JTextField();
        EmailLbl = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        CommunityLbl = new javax.swing.JLabel();
        CommunityInput = new javax.swing.JComboBox<>();
        CityLbl = new javax.swing.JLabel();
        CityInput = new javax.swing.JTextField();
        HouseNoLbl = new javax.swing.JLabel();
        HouseNoInput = new javax.swing.JTextField();
        StreetLbl = new javax.swing.JLabel();
        StreetInput = new javax.swing.JTextField();
        PassLbl = new javax.swing.JLabel();
        PassInput = new javax.swing.JTextField();
        ConfPasslbl = new javax.swing.JLabel();
        ConfPassInput = new javax.swing.JTextField();
        AddPersonSubmitButton = new javax.swing.JButton();
        IdErrMsg = new javax.swing.JLabel();
        ContactErrMsg = new javax.swing.JLabel();
        EmailErrMsg = new javax.swing.JLabel();
        PassErrMsg = new javax.swing.JLabel();
        ConfPassErrMsg = new javax.swing.JLabel();

        WorkAreaSplit.setBackground(new java.awt.Color(0, 51, 51));
        WorkAreaSplit.setDividerLocation(200);

        ButtonsArea.setBackground(new java.awt.Color(0, 204, 204));
        ButtonsArea.setPreferredSize(new java.awt.Dimension(200, 795));

        AddPersonButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddPersonButton.setForeground(new java.awt.Color(0, 102, 102));
        AddPersonButton.setText("Add Person");
        AddPersonButton.setMaximumSize(new java.awt.Dimension(120, 50));
        AddPersonButton.setMinimumSize(new java.awt.Dimension(120, 50));
        AddPersonButton.setPreferredSize(new java.awt.Dimension(200, 60));
        AddPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPersonButtonActionPerformed(evt);
            }
        });

        PersonDirectoryButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PersonDirectoryButton.setForeground(new java.awt.Color(0, 102, 102));
        PersonDirectoryButton.setText("Person Directory");
        PersonDirectoryButton.setMaximumSize(new java.awt.Dimension(120, 50));
        PersonDirectoryButton.setMinimumSize(new java.awt.Dimension(120, 50));
        PersonDirectoryButton.setPreferredSize(new java.awt.Dimension(200, 60));
        PersonDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonDirectoryButtonActionPerformed(evt);
            }
        });

        PatientDirectoryButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PatientDirectoryButton.setForeground(new java.awt.Color(0, 102, 102));
        PatientDirectoryButton.setText("Patient Directory");
        PatientDirectoryButton.setMaximumSize(new java.awt.Dimension(120, 50));
        PatientDirectoryButton.setMinimumSize(new java.awt.Dimension(120, 50));
        PatientDirectoryButton.setPreferredSize(new java.awt.Dimension(200, 60));
        PatientDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientDirectoryButtonActionPerformed(evt);
            }
        });

        DoctorDirectoryButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DoctorDirectoryButton.setForeground(new java.awt.Color(0, 102, 102));
        DoctorDirectoryButton.setText("Doctor Directory");
        DoctorDirectoryButton.setMaximumSize(new java.awt.Dimension(120, 50));
        DoctorDirectoryButton.setMinimumSize(new java.awt.Dimension(120, 50));
        DoctorDirectoryButton.setPreferredSize(new java.awt.Dimension(200, 60));
        DoctorDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorDirectoryButtonActionPerformed(evt);
            }
        });

        HospitalAdminsButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        HospitalAdminsButton.setForeground(new java.awt.Color(0, 102, 102));
        HospitalAdminsButton.setText("Hospital Admins");
        HospitalAdminsButton.setMaximumSize(new java.awt.Dimension(120, 50));
        HospitalAdminsButton.setMinimumSize(new java.awt.Dimension(120, 50));
        HospitalAdminsButton.setPreferredSize(new java.awt.Dimension(200, 60));
        HospitalAdminsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalAdminsButtonActionPerformed(evt);
            }
        });

        CommunityAdminsButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CommunityAdminsButton.setForeground(new java.awt.Color(0, 102, 102));
        CommunityAdminsButton.setText("Community Admins");
        CommunityAdminsButton.setMaximumSize(new java.awt.Dimension(120, 50));
        CommunityAdminsButton.setMinimumSize(new java.awt.Dimension(120, 50));
        CommunityAdminsButton.setPreferredSize(new java.awt.Dimension(200, 60));
        CommunityAdminsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityAdminsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsAreaLayout = new javax.swing.GroupLayout(ButtonsArea);
        ButtonsArea.setLayout(ButtonsAreaLayout);
        ButtonsAreaLayout.setHorizontalGroup(
            ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsAreaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CommunityAdminsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalAdminsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ButtonsAreaLayout.setVerticalGroup(
            ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsAreaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(AddPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PersonDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoctorDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HospitalAdminsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CommunityAdminsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        WorkAreaSplit.setLeftComponent(ButtonsArea);

        ActionsArea.setBackground(new java.awt.Color(255, 255, 255));
        ActionsArea.setPreferredSize(new java.awt.Dimension(995, 795));

        TypeLbl.setBackground(new java.awt.Color(255, 255, 255));
        TypeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TypeLbl.setForeground(new java.awt.Color(102, 102, 102));
        TypeLbl.setText("Type:");
        TypeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        TypeInput.setBackground(new java.awt.Color(238, 238, 238));
        TypeInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Person", "Patient", "Doctor", "Community Admin", "Hospital Admin" }));
        TypeInput.setPreferredSize(new java.awt.Dimension(64, 23));
        TypeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeInputActionPerformed(evt);
            }
        });

        NameLbl.setBackground(new java.awt.Color(255, 255, 255));
        NameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(102, 102, 102));
        NameLbl.setText("Name:");
        NameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        NameInput.setBackground(new java.awt.Color(238, 238, 238));
        NameInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        NameInput.setForeground(new java.awt.Color(51, 51, 51));
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        IdLbl.setBackground(new java.awt.Color(255, 255, 255));
        IdLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IdLbl.setForeground(new java.awt.Color(102, 102, 102));
        IdLbl.setText("ID:");
        IdLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        IdInput.setBackground(new java.awt.Color(238, 238, 238));
        IdInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        IdInput.setForeground(new java.awt.Color(51, 51, 51));
        IdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdInputActionPerformed(evt);
            }
        });

        AgeLbl.setBackground(new java.awt.Color(255, 255, 255));
        AgeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgeLbl.setForeground(new java.awt.Color(102, 102, 102));
        AgeLbl.setText("Age:");
        AgeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        AgeInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        AgeInput.setModel(new javax.swing.SpinnerNumberModel(22, 18, 62, 1));

        GenderLbl.setBackground(new java.awt.Color(255, 255, 255));
        GenderLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GenderLbl.setForeground(new java.awt.Color(102, 102, 102));
        GenderLbl.setText("Gender:");
        GenderLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        FemaleRadio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        FemaleRadio.setForeground(new java.awt.Color(51, 51, 51));
        FemaleRadio.setText("Female");

        MaleRadio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        MaleRadio.setForeground(new java.awt.Color(51, 51, 51));
        MaleRadio.setText("Male");
        MaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioActionPerformed(evt);
            }
        });

        OtherRadio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        OtherRadio.setForeground(new java.awt.Color(51, 51, 51));
        OtherRadio.setText("Other");
        OtherRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherRadioActionPerformed(evt);
            }
        });

        ContactLbl.setBackground(new java.awt.Color(255, 255, 255));
        ContactLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContactLbl.setForeground(new java.awt.Color(102, 102, 102));
        ContactLbl.setText("Contact:");
        ContactLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ContactInput.setBackground(new java.awt.Color(238, 238, 238));
        ContactInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactInput.setForeground(new java.awt.Color(51, 51, 51));
        ContactInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactInputActionPerformed(evt);
            }
        });

        EmailLbl.setBackground(new java.awt.Color(255, 255, 255));
        EmailLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(102, 102, 102));
        EmailLbl.setText("Email:");
        EmailLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        EmailInput.setBackground(new java.awt.Color(238, 238, 238));
        EmailInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        EmailInput.setForeground(new java.awt.Color(51, 51, 51));
        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });

        CommunityLbl.setBackground(new java.awt.Color(255, 255, 255));
        CommunityLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CommunityLbl.setForeground(new java.awt.Color(102, 102, 102));
        CommunityLbl.setText("Community:");
        CommunityLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        CommunityInput.setBackground(new java.awt.Color(238, 238, 238));
        CommunityInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CommunityInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Community" }));
        CommunityInput.setPreferredSize(new java.awt.Dimension(64, 23));
        CommunityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityInputActionPerformed(evt);
            }
        });

        CityLbl.setBackground(new java.awt.Color(255, 255, 255));
        CityLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CityLbl.setForeground(new java.awt.Color(102, 102, 102));
        CityLbl.setText("City:");
        CityLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        CityInput.setBackground(new java.awt.Color(238, 238, 238));
        CityInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CityInput.setForeground(new java.awt.Color(51, 51, 51));
        CityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityInputActionPerformed(evt);
            }
        });

        HouseNoLbl.setBackground(new java.awt.Color(255, 255, 255));
        HouseNoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HouseNoLbl.setForeground(new java.awt.Color(102, 102, 102));
        HouseNoLbl.setText("House No:");
        HouseNoLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        HouseNoInput.setBackground(new java.awt.Color(238, 238, 238));
        HouseNoInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        HouseNoInput.setForeground(new java.awt.Color(51, 51, 51));
        HouseNoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseNoInputActionPerformed(evt);
            }
        });

        StreetLbl.setBackground(new java.awt.Color(255, 255, 255));
        StreetLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StreetLbl.setForeground(new java.awt.Color(102, 102, 102));
        StreetLbl.setText("Street:");
        StreetLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        StreetInput.setBackground(new java.awt.Color(238, 238, 238));
        StreetInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        StreetInput.setForeground(new java.awt.Color(51, 51, 51));
        StreetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetInputActionPerformed(evt);
            }
        });

        PassLbl.setBackground(new java.awt.Color(255, 255, 255));
        PassLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassLbl.setForeground(new java.awt.Color(102, 102, 102));
        PassLbl.setText("Password:");
        PassLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        PassInput.setBackground(new java.awt.Color(238, 238, 238));
        PassInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        PassInput.setForeground(new java.awt.Color(51, 51, 51));
        PassInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassInputActionPerformed(evt);
            }
        });

        ConfPasslbl.setBackground(new java.awt.Color(255, 255, 255));
        ConfPasslbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConfPasslbl.setForeground(new java.awt.Color(102, 102, 102));
        ConfPasslbl.setText("Confirm Password:");
        ConfPasslbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ConfPassInput.setBackground(new java.awt.Color(238, 238, 238));
        ConfPassInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ConfPassInput.setForeground(new java.awt.Color(51, 51, 51));
        ConfPassInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfPassInputActionPerformed(evt);
            }
        });

        AddPersonSubmitButton.setBackground(new java.awt.Color(0, 102, 102));
        AddPersonSubmitButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddPersonSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        AddPersonSubmitButton.setText("ADD");
        AddPersonSubmitButton.setMaximumSize(new java.awt.Dimension(120, 50));
        AddPersonSubmitButton.setMinimumSize(new java.awt.Dimension(120, 50));
        AddPersonSubmitButton.setPreferredSize(new java.awt.Dimension(200, 60));
        AddPersonSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPersonSubmitButtonActionPerformed(evt);
            }
        });

        IdErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        IdErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        IdErrMsg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        IdErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ContactErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        ContactErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ContactErrMsg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        ContactErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        EmailErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        EmailErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        EmailErrMsg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        EmailErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        PassErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        PassErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PassErrMsg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        PassErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ConfPassErrMsg.setBackground(new java.awt.Color(255, 255, 255));
        ConfPassErrMsg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ConfPassErrMsg.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        ConfPassErrMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout ActionsAreaLayout = new javax.swing.GroupLayout(ActionsArea);
        ActionsArea.setLayout(ActionsAreaLayout);
        ActionsAreaLayout.setHorizontalGroup(
            ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionsAreaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActionsAreaLayout.createSequentialGroup()
                        .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLbl)
                            .addComponent(TypeLbl)
                            .addComponent(IdLbl)
                            .addComponent(GenderLbl)
                            .addComponent(ContactLbl)
                            .addComponent(CommunityLbl)
                            .addComponent(CityLbl)
                            .addComponent(StreetLbl)
                            .addComponent(EmailLbl)
                            .addComponent(ConfPasslbl))
                        .addGap(10, 10, 10)
                        .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ActionsAreaLayout.createSequentialGroup()
                                .addComponent(FemaleRadio)
                                .addGap(18, 18, 18)
                                .addComponent(MaleRadio)
                                .addGap(18, 18, 18)
                                .addComponent(OtherRadio))
                            .addComponent(TypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ActionsAreaLayout.createSequentialGroup()
                                .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(AgeLbl)
                                .addGap(10, 10, 10)
                                .addComponent(AgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CommunityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ActionsAreaLayout.createSequentialGroup()
                                .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(HouseNoLbl)
                                .addGap(10, 10, 10)
                                .addComponent(HouseNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ContactInput)
                            .addComponent(StreetInput)
                            .addComponent(NameInput)
                            .addComponent(EmailInput)
                            .addComponent(PassInput)
                            .addComponent(ConfPassInput, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(PassLbl))
                .addGap(18, 18, 18)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddPersonSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfPassErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ActionsAreaLayout.setVerticalGroup(
            ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionsAreaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLbl)
                    .addComponent(TypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLbl)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLbl)
                    .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeLbl)
                    .addComponent(AgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FemaleRadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GenderLbl)
                        .addComponent(MaleRadio)
                        .addComponent(OtherRadio)))
                .addGap(30, 30, 30)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ContactLbl)
                        .addComponent(ContactInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLbl)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommunityLbl)
                    .addComponent(CommunityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLbl)
                    .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HouseNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HouseNoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetLbl)
                    .addComponent(StreetInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PassLbl)
                        .addComponent(PassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfPasslbl)
                    .addComponent(ConfPassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfPassErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(AddPersonSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );

        WorkAreaSplit.setRightComponent(ActionsArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(WorkAreaSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(WorkAreaSplit)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPersonButtonActionPerformed
        // TODO add your handling code here:
        AddPerson addPerson = new AddPerson(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(addPerson);
    }//GEN-LAST:event_AddPersonButtonActionPerformed

    private void PersonDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonDirectoryButtonActionPerformed
        // TODO add your handling code here:
        PersonDirectory personDirectory = new PersonDirectory(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(personDirectory);
    }//GEN-LAST:event_PersonDirectoryButtonActionPerformed

    private void PatientDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientDirectoryButtonActionPerformed
        // TODO add your handling code here:
        PatientDirectory patientDirectory = new PatientDirectory(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(patientDirectory);
    }//GEN-LAST:event_PatientDirectoryButtonActionPerformed

    private void DoctorDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorDirectoryButtonActionPerformed
        // TODO add your handling code here:
        DoctorDirectory doctorDirectory = new DoctorDirectory(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(doctorDirectory);
    }//GEN-LAST:event_DoctorDirectoryButtonActionPerformed

    private void HospitalAdminsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalAdminsButtonActionPerformed
        // TODO add your handling code here:
        HospitalAdmins hospitalAdmins = new HospitalAdmins(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(hospitalAdmins);
    }//GEN-LAST:event_HospitalAdminsButtonActionPerformed

    private void CommunityAdminsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityAdminsButtonActionPerformed
        // TODO add your handling code here:
        CommunityAdmins communityAdmins = new CommunityAdmins(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(communityAdmins);
    }//GEN-LAST:event_CommunityAdminsButtonActionPerformed

    private void TypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeInputActionPerformed

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void IdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdInputActionPerformed

    private void MaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioActionPerformed

    private void OtherRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtherRadioActionPerformed

    private void ContactInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactInputActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void CommunityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityInputActionPerformed

    private void CityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityInputActionPerformed

    private void HouseNoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseNoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HouseNoInputActionPerformed

    private void StreetInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetInputActionPerformed

    private void PassInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassInputActionPerformed

    private void ConfPassInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfPassInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfPassInputActionPerformed

    private void AddPersonSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPersonSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPersonSubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionsArea;
    private javax.swing.JButton AddPersonButton;
    private javax.swing.JButton AddPersonSubmitButton;
    private javax.swing.JSpinner AgeInput;
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JPanel ButtonsArea;
    private javax.swing.JTextField CityInput;
    private javax.swing.JLabel CityLbl;
    private javax.swing.JButton CommunityAdminsButton;
    private javax.swing.JComboBox<String> CommunityInput;
    private javax.swing.JLabel CommunityLbl;
    private javax.swing.JLabel ConfPassErrMsg;
    private javax.swing.JTextField ConfPassInput;
    private javax.swing.JLabel ConfPasslbl;
    private javax.swing.JLabel ContactErrMsg;
    private javax.swing.JTextField ContactInput;
    private javax.swing.JLabel ContactLbl;
    private javax.swing.JButton DoctorDirectoryButton;
    private javax.swing.JLabel EmailErrMsg;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JButton HospitalAdminsButton;
    private javax.swing.JTextField HouseNoInput;
    private javax.swing.JLabel HouseNoLbl;
    private javax.swing.JLabel IdErrMsg;
    private javax.swing.JTextField IdInput;
    private javax.swing.JLabel IdLbl;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JRadioButton OtherRadio;
    private javax.swing.JLabel PassErrMsg;
    private javax.swing.JTextField PassInput;
    private javax.swing.JLabel PassLbl;
    private javax.swing.JButton PatientDirectoryButton;
    private javax.swing.JButton PersonDirectoryButton;
    private javax.swing.JTextField StreetInput;
    private javax.swing.JLabel StreetLbl;
    private javax.swing.JComboBox<String> TypeInput;
    private javax.swing.JLabel TypeLbl;
    private javax.swing.JSplitPane WorkAreaSplit;
    // End of variables declaration//GEN-END:variables
}
