/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import model.EncounterHistory;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author vishwashah
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
   PersonDirectory person_Dir;
    PatientDirectory patient_Dir;
    EncounterHistory encounter_history;
    PatientDirectory ab_patient;
    EncounterHistory ab_encounter;
    public MainJframe() {
        initComponents();
        
        person_Dir = getDataFromCSV();
                
        patient_Dir = new PatientDirectory();
        encounter_history = new EncounterHistory();
        ab_patient = new PatientDirectory();
        ab_encounter = new EncounterHistory();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        ControlArea = new javax.swing.JPanel();
        btnPatientDatabase = new javax.swing.JButton();
        btnPersonDatabase = new javax.swing.JButton();
        btnAbnormalCases = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        WorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlArea.setBackground(new java.awt.Color(0, 153, 153));

        btnPatientDatabase.setText("Patient");
        btnPatientDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDatabaseActionPerformed(evt);
            }
        });

        btnPersonDatabase.setText(" Person");
        btnPersonDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonDatabaseActionPerformed(evt);
            }
        });

        btnAbnormalCases.setText("Abnormal Cases");
        btnAbnormalCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbnormalCasesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlAreaLayout = new javax.swing.GroupLayout(ControlArea);
        ControlArea.setLayout(ControlAreaLayout);
        ControlAreaLayout.setHorizontalGroup(
            ControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPersonDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPatientDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbnormalCases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlAreaLayout.setVerticalGroup(
            ControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlAreaLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnPatientDatabase)
                .addGap(61, 61, 61)
                .addComponent(btnPersonDatabase)
                .addGap(57, 57, 57)
                .addComponent(btnAbnormalCases)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(ControlArea);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Login Page");
        SplitPanel.setRightComponent(jLabel1);

        WorkArea.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout WorkAreaLayout = new javax.swing.GroupLayout(WorkArea);
        WorkArea.setLayout(WorkAreaLayout);
        WorkAreaLayout.setHorizontalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        WorkAreaLayout.setVerticalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        SplitPanel.setRightComponent(WorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonDatabaseActionPerformed
        // TODO add your handling code here:
      AddPerson viewDirectory = new AddPerson(person_Dir,patient_Dir,encounter_history);
        
        SplitPanel.setRightComponent(viewDirectory);
    }//GEN-LAST:event_btnPersonDatabaseActionPerformed


    private void btnAbnormalCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbnormalCasesActionPerformed
        // TODO add your handling code here:
       ViewAbnormalities abnormalCases = new ViewAbnormalities(ab_patient,ab_encounter,person_Dir);
        SplitPanel.setRightComponent(abnormalCases);
    }//GEN-LAST:event_btnAbnormalCasesActionPerformed

    private void btnPatientDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDatabaseActionPerformed
        // TODO add your handling code here:
        AddPatient viewPatDirectory = new AddPatient(patient_Dir, encounter_history,ab_patient,ab_encounter);
        SplitPanel.setRightComponent(viewPatDirectory);
                                               
    }//GEN-LAST:event_btnPatientDatabaseActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlArea;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JButton btnAbnormalCases;
    private javax.swing.JButton btnPatientDatabase;
    private javax.swing.JButton btnPersonDatabase;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
 private PersonDirectory getDataFromCSV() {
       PersonDirectory csvData = new PersonDirectory();
        Path pathToFile = Paths.get("C:\\Users\\shah0\\OneDrive\\Documents\\NetBeansProjects\\Assignment_4\\data.txt");
        try(BufferedReader br = Files.newBufferedReader(pathToFile,StandardCharsets.US_ASCII)){
            String line = br.readLine();
            while(line!= null){
            String[] attributes = line.split(" ");
            Person person = addPerson(attributes);
            csvData.addNewPerson(person);
            line = br.readLine();
            
            }
        }catch(IOException ioe){
        ioe.printStackTrace();
        }
        return csvData;
    }

    private Person addPerson(String[] attributes) {
        Person person = new Person();
        person.setFirstname(attributes[0]);
        person.setLastname(attributes[1]);
        person.setPersonage(Integer.parseInt(attributes[2]));
        person.setPersoncityname(attributes[3]);
        person.setPersoncommunityname(attributes[4]);
        person.setPersonhouseno(Integer.parseInt(attributes[5]));
        return person;
    }
}
