/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CommunityAdmins;

import Classes.BookingArray;
import Classes.CommunityArray;
import Classes.EncounterArray;
import Classes.HospitalArray;
import Classes.PersonArray;

/**
 *
 * @author vishwashah
 */
public class ComAdminMainFrame extends javax.swing.JPanel {

    /**
     * Creates new form ComAdminMainFrame
     */
    PersonArray person;
    HospitalArray hospital;
    CommunityArray community;
    BookingArray booking;
    EncounterArray encounter;
    
    public ComAdminMainFrame(PersonArray person, HospitalArray hospital, CommunityArray community, BookingArray booking, EncounterArray encounter) {
        initComponents();
        
        this.person = person;
        this.hospital = hospital;
        this.community = community;
        this.booking = booking;
        this.encounter = encounter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WorkAreaSplit = new javax.swing.JSplitPane();
        ButtonsArea = new javax.swing.JPanel();
        AddCommunityButton = new javax.swing.JButton();
        CommunitiesButton = new javax.swing.JButton();
        ActionsArea = new javax.swing.JPanel();
        NameLbl = new javax.swing.JLabel();
        IdLbl = new javax.swing.JLabel();
        IdInput = new javax.swing.JTextField();
        NameInput = new javax.swing.JTextField();
        CityLbl = new javax.swing.JLabel();
        CityInput = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();

        WorkAreaSplit.setBackground(new java.awt.Color(0, 51, 51));
        WorkAreaSplit.setDividerLocation(200);

        ButtonsArea.setBackground(new java.awt.Color(0, 204, 204));
        ButtonsArea.setPreferredSize(new java.awt.Dimension(200, 795));

        AddCommunityButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddCommunityButton.setForeground(new java.awt.Color(0, 102, 102));
        AddCommunityButton.setText("Add Community");
        AddCommunityButton.setMaximumSize(new java.awt.Dimension(120, 50));
        AddCommunityButton.setMinimumSize(new java.awt.Dimension(120, 50));
        AddCommunityButton.setPreferredSize(new java.awt.Dimension(200, 60));
        AddCommunityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCommunityButtonActionPerformed(evt);
            }
        });

        CommunitiesButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CommunitiesButton.setForeground(new java.awt.Color(0, 102, 102));
        CommunitiesButton.setText("Communities");
        CommunitiesButton.setToolTipText("");
        CommunitiesButton.setMaximumSize(new java.awt.Dimension(120, 50));
        CommunitiesButton.setMinimumSize(new java.awt.Dimension(120, 50));
        CommunitiesButton.setPreferredSize(new java.awt.Dimension(200, 60));
        CommunitiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunitiesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsAreaLayout = new javax.swing.GroupLayout(ButtonsArea);
        ButtonsArea.setLayout(ButtonsAreaLayout);
        ButtonsAreaLayout.setHorizontalGroup(
            ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsAreaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AddCommunityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CommunitiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ButtonsAreaLayout.setVerticalGroup(
            ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsAreaLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(CommunitiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddCommunityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
        );

        WorkAreaSplit.setLeftComponent(ButtonsArea);

        ActionsArea.setBackground(new java.awt.Color(255, 255, 255));
        ActionsArea.setPreferredSize(new java.awt.Dimension(995, 795));

        NameLbl.setBackground(new java.awt.Color(255, 255, 255));
        NameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLbl.setText("Name:");
        NameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        IdLbl.setBackground(new java.awt.Color(255, 255, 255));
        IdLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IdLbl.setText("ID:");
        IdLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        IdInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        IdInput.setForeground(new java.awt.Color(51, 51, 51));
        IdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdInputActionPerformed(evt);
            }
        });

        NameInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        NameInput.setForeground(new java.awt.Color(51, 51, 51));
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        CityLbl.setBackground(new java.awt.Color(255, 255, 255));
        CityLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CityLbl.setText("City:");
        CityLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        CityInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CityInput.setForeground(new java.awt.Color(51, 51, 51));
        CityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityInputActionPerformed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Symbol", 1, 13)); // NOI18N
        AddButton.setForeground(new java.awt.Color(0, 153, 153));
        AddButton.setText("ADD");
        AddButton.setMaximumSize(new java.awt.Dimension(120, 50));
        AddButton.setMinimumSize(new java.awt.Dimension(120, 50));
        AddButton.setPreferredSize(new java.awt.Dimension(200, 60));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionsAreaLayout = new javax.swing.GroupLayout(ActionsArea);
        ActionsArea.setLayout(ActionsAreaLayout);
        ActionsAreaLayout.setHorizontalGroup(
            ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionsAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(ActionsAreaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdLbl)
                    .addGroup(ActionsAreaLayout.createSequentialGroup()
                        .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLbl))
                        .addGap(26, 26, 26)
                        .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        ActionsAreaLayout.setVerticalGroup(
            ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionsAreaLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLbl))
                .addGap(39, 39, 39)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLbl))
                .addGap(41, 41, 41)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        WorkAreaSplit.setRightComponent(ActionsArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(WorkAreaSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(WorkAreaSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddCommunityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCommunityButtonActionPerformed
        // TODO add your handling code here:
        AddCommunity addCommunity = new AddCommunity(person, hospital,community, booking, encounter);
       
        WorkAreaSplit.setRightComponent(addCommunity);
    }//GEN-LAST:event_AddCommunityButtonActionPerformed

    private void CommunitiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunitiesButtonActionPerformed
        // TODO add your handling code here:
        CommunityDirectory communityDirectory = new CommunityDirectory(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(communityDirectory);
    }//GEN-LAST:event_CommunitiesButtonActionPerformed

    private void IdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdInputActionPerformed

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void CityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityInputActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionsArea;
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddCommunityButton;
    private javax.swing.JPanel ButtonsArea;
    private javax.swing.JTextField CityInput;
    private javax.swing.JLabel CityLbl;
    private javax.swing.JButton CommunitiesButton;
    private javax.swing.JTextField IdInput;
    private javax.swing.JLabel IdLbl;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JSplitPane WorkAreaSplit;
    // End of variables declaration//GEN-END:variables
}
