/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patient;

import Classes.BookingArray;
import Classes.CommunityArray;
import Classes.EncounterArray;
import Classes.HospitalArray;
import Classes.PersonArray;

/**
 *
 * @author vishwashah
 */
public class PatientMainFrame extends javax.swing.JPanel {

    /**
     * Creates new form PatientMainFrame
     */
    PersonArray person;
    HospitalArray hospital;
    CommunityArray community;
    BookingArray booking;
    EncounterArray encounter;
    
    public PatientMainFrame(PersonArray person, HospitalArray hospital, CommunityArray community, BookingArray booking, EncounterArray encounter) {
        initComponents();
        
        this.person = person;
        this.hospital = hospital;
        this.community = community;
        this.booking = booking;
        this.encounter = encounter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WorkAreaSplit = new javax.swing.JSplitPane();
        ButtonsArea = new javax.swing.JPanel();
        ViewProfileButton = new javax.swing.JButton();
        BookApButton = new javax.swing.JButton();
        ViewVitalSignsButton = new javax.swing.JButton();
        ActionsArea = new javax.swing.JPanel();
        HosTableScroll = new javax.swing.JScrollPane();
        HosTable = new javax.swing.JTable();
        Desciption1 = new javax.swing.JLabel();
        Desciption2 = new javax.swing.JLabel();
        SeleHosButton = new javax.swing.JButton();
        SelectedHos = new javax.swing.JTextField();
        DocTableScroll = new javax.swing.JScrollPane();
        DocTable = new javax.swing.JTable();
        Desciption3 = new javax.swing.JLabel();
        Desciption4 = new javax.swing.JLabel();
        SeleDocButton = new javax.swing.JButton();
        SelectedDoc = new javax.swing.JTextField();
        BookAppoButton = new javax.swing.JButton();

        WorkAreaSplit.setBackground(new java.awt.Color(64, 64, 141));
        WorkAreaSplit.setDividerLocation(200);

        ButtonsArea.setBackground(new java.awt.Color(225, 225, 255));
        ButtonsArea.setPreferredSize(new java.awt.Dimension(200, 795));

        ViewProfileButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ViewProfileButton.setForeground(new java.awt.Color(0, 102, 102));
        ViewProfileButton.setText("View Profile");
        ViewProfileButton.setMaximumSize(new java.awt.Dimension(120, 50));
        ViewProfileButton.setMinimumSize(new java.awt.Dimension(120, 50));
        ViewProfileButton.setPreferredSize(new java.awt.Dimension(200, 60));
        ViewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileButtonActionPerformed(evt);
            }
        });

        BookApButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BookApButton.setForeground(new java.awt.Color(0, 102, 102));
        BookApButton.setText("Book Appoinment");
        BookApButton.setMaximumSize(new java.awt.Dimension(120, 50));
        BookApButton.setMinimumSize(new java.awt.Dimension(120, 50));
        BookApButton.setPreferredSize(new java.awt.Dimension(200, 60));
        BookApButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookApButtonActionPerformed(evt);
            }
        });

        ViewVitalSignsButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ViewVitalSignsButton.setForeground(new java.awt.Color(0, 102, 102));
        ViewVitalSignsButton.setText("Encounter History");
        ViewVitalSignsButton.setMaximumSize(new java.awt.Dimension(120, 50));
        ViewVitalSignsButton.setMinimumSize(new java.awt.Dimension(120, 50));
        ViewVitalSignsButton.setPreferredSize(new java.awt.Dimension(200, 60));
        ViewVitalSignsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewVitalSignsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsAreaLayout = new javax.swing.GroupLayout(ButtonsArea);
        ButtonsArea.setLayout(ButtonsAreaLayout);
        ButtonsAreaLayout.setHorizontalGroup(
            ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsAreaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewVitalSignsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookApButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ButtonsAreaLayout.setVerticalGroup(
            ButtonsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsAreaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(BookApButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewVitalSignsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        WorkAreaSplit.setLeftComponent(ButtonsArea);

        ActionsArea.setBackground(new java.awt.Color(255, 255, 255));
        ActionsArea.setPreferredSize(new java.awt.Dimension(995, 795));

        HosTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        HosTable.setForeground(new java.awt.Color(51, 51, 51));
        HosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hospital", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        HosTableScroll.setViewportView(HosTable);

        Desciption1.setFont(new java.awt.Font("Symbol", 0, 24)); // NOI18N
        Desciption1.setForeground(new java.awt.Color(0, 153, 153));
        Desciption1.setText("Hospitals Near You");

        Desciption2.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        Desciption2.setForeground(new java.awt.Color(0, 102, 102));
        Desciption2.setText("Select Hospital ");

        SeleHosButton.setBackground(new java.awt.Color(0, 153, 153));
        SeleHosButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SeleHosButton.setForeground(new java.awt.Color(255, 255, 255));
        SeleHosButton.setText("SELECT HOSPITAL");
        SeleHosButton.setMaximumSize(new java.awt.Dimension(120, 50));
        SeleHosButton.setMinimumSize(new java.awt.Dimension(120, 50));
        SeleHosButton.setPreferredSize(new java.awt.Dimension(200, 60));
        SeleHosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleHosButtonActionPerformed(evt);
            }
        });

        SelectedHos.setBackground(new java.awt.Color(238, 238, 238));
        SelectedHos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        SelectedHos.setForeground(new java.awt.Color(51, 51, 51));
        SelectedHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedHosActionPerformed(evt);
            }
        });

        DocTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        DocTable.setForeground(new java.awt.Color(51, 51, 51));
        DocTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DocTableScroll.setViewportView(DocTable);

        Desciption3.setFont(new java.awt.Font("Symbol", 0, 24)); // NOI18N
        Desciption3.setForeground(new java.awt.Color(0, 153, 153));
        Desciption3.setText("Doctors Near You");

        Desciption4.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        Desciption4.setForeground(new java.awt.Color(0, 153, 153));
        Desciption4.setText("Select Hospital :");

        SeleDocButton.setBackground(new java.awt.Color(0, 153, 153));
        SeleDocButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SeleDocButton.setForeground(new java.awt.Color(255, 255, 255));
        SeleDocButton.setText("SELECT DOCTOR");
        SeleDocButton.setMaximumSize(new java.awt.Dimension(120, 50));
        SeleDocButton.setMinimumSize(new java.awt.Dimension(120, 50));
        SeleDocButton.setPreferredSize(new java.awt.Dimension(200, 60));
        SeleDocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleDocButtonActionPerformed(evt);
            }
        });

        SelectedDoc.setBackground(new java.awt.Color(238, 238, 238));
        SelectedDoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        SelectedDoc.setForeground(new java.awt.Color(51, 51, 51));
        SelectedDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedDocActionPerformed(evt);
            }
        });

        BookAppoButton.setBackground(new java.awt.Color(0, 153, 153));
        BookAppoButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BookAppoButton.setForeground(new java.awt.Color(255, 255, 255));
        BookAppoButton.setText("BOOK APPOINTMENT");
        BookAppoButton.setMaximumSize(new java.awt.Dimension(120, 50));
        BookAppoButton.setMinimumSize(new java.awt.Dimension(120, 50));
        BookAppoButton.setPreferredSize(new java.awt.Dimension(200, 60));
        BookAppoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionsAreaLayout = new javax.swing.GroupLayout(ActionsArea);
        ActionsArea.setLayout(ActionsAreaLayout);
        ActionsAreaLayout.setHorizontalGroup(
            ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionsAreaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BookAppoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ActionsAreaLayout.createSequentialGroup()
                            .addComponent(SeleHosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SelectedHos))
                        .addComponent(Desciption2)
                        .addComponent(Desciption1)
                        .addComponent(HosTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addComponent(DocTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addComponent(Desciption3)
                        .addComponent(Desciption4)
                        .addGroup(ActionsAreaLayout.createSequentialGroup()
                            .addComponent(SeleDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SelectedDoc))))
                .addGap(30, 30, 30))
        );
        ActionsAreaLayout.setVerticalGroup(
            ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionsAreaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Desciption1)
                .addGap(20, 20, 20)
                .addComponent(HosTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Desciption2)
                .addGap(30, 30, 30)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectedHos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleHosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(Desciption3)
                .addGap(20, 20, 20)
                .addComponent(DocTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ActionsAreaLayout.createSequentialGroup()
                        .addComponent(Desciption4)
                        .addGap(61, 61, 61))
                    .addGroup(ActionsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SelectedDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SeleDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(BookAppoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        WorkAreaSplit.setRightComponent(ActionsArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WorkAreaSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WorkAreaSplit)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileButtonActionPerformed
        // TODO add your handling code here:
        ViewProfile viewProfile = new ViewProfile(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(viewProfile);
    }//GEN-LAST:event_ViewProfileButtonActionPerformed

    private void BookApButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookApButtonActionPerformed
        // TODO add your handling code here:
        BookAppointment hospitalsNearMe = new BookAppointment(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(hospitalsNearMe);
    }//GEN-LAST:event_BookApButtonActionPerformed

    private void ViewVitalSignsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewVitalSignsButtonActionPerformed
        // TODO add your handling code here:
        EncounterHistory encounterHistory = new EncounterHistory(person, hospital, community, booking, encounter);
        WorkAreaSplit.setRightComponent(encounterHistory);
    }//GEN-LAST:event_ViewVitalSignsButtonActionPerformed

    private void SeleHosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleHosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleHosButtonActionPerformed

    private void SelectedHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedHosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedHosActionPerformed

    private void SeleDocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleDocButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleDocButtonActionPerformed

    private void SelectedDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedDocActionPerformed

    private void BookAppoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookAppoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionsArea;
    private javax.swing.JButton BookApButton;
    private javax.swing.JButton BookAppoButton;
    private javax.swing.JPanel ButtonsArea;
    private javax.swing.JLabel Desciption1;
    private javax.swing.JLabel Desciption2;
    private javax.swing.JLabel Desciption3;
    private javax.swing.JLabel Desciption4;
    private javax.swing.JTable DocTable;
    private javax.swing.JScrollPane DocTableScroll;
    private javax.swing.JTable HosTable;
    private javax.swing.JScrollPane HosTableScroll;
    private javax.swing.JButton SeleDocButton;
    private javax.swing.JButton SeleHosButton;
    private javax.swing.JTextField SelectedDoc;
    private javax.swing.JTextField SelectedHos;
    private javax.swing.JButton ViewProfileButton;
    private javax.swing.JButton ViewVitalSignsButton;
    private javax.swing.JSplitPane WorkAreaSplit;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
