/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patient;

import ApplicationDesign.LogIn;
import Classes.BookingArray;
import Classes.CommunityArray;
import Classes.EncounterArray;
import Classes.HospitalArray;
import Classes.Person;
import Classes.PersonArray;
import SystemAdmin.PersonDirectory;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vishwashah
 */
public class ViewProfile extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfile
     */
   PersonArray person;
    HospitalArray hospital;
    CommunityArray community;
    BookingArray booking;
    EncounterArray encounter;
    
    public ViewProfile(PersonArray person, HospitalArray hospital, CommunityArray community, BookingArray booking, EncounterArray encounter) {
        initComponents();
        
        this.person = person;
        this.hospital = hospital;
        this.community = community;
        this.booking = booking;
        this.encounter = encounter;
        
        addCommuniy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameLbl = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        IdLbl = new javax.swing.JLabel();
        IdInput = new javax.swing.JTextField();
        AgeLbl = new javax.swing.JLabel();
        AgeInput = new javax.swing.JSpinner();
        GenderLbl = new javax.swing.JLabel();
        ContactLbl = new javax.swing.JLabel();
        ContactInput = new javax.swing.JTextField();
        EmailLbl = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        CommunityLbl = new javax.swing.JLabel();
        CommunityInput = new javax.swing.JComboBox<>();
        CityLbl = new javax.swing.JLabel();
        CityInput = new javax.swing.JTextField();
        HouseNoLbl = new javax.swing.JLabel();
        HouseNoInput = new javax.swing.JTextField();
        StreetLbl = new javax.swing.JLabel();
        StreetInput = new javax.swing.JTextField();
        GenderInput = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        NameLbl.setBackground(new java.awt.Color(255, 255, 255));
        NameLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        NameLbl.setText("Name:");
        NameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        NameInput.setBackground(new java.awt.Color(238, 238, 238));
        NameInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        NameInput.setForeground(new java.awt.Color(51, 51, 51));
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        IdLbl.setBackground(new java.awt.Color(255, 255, 255));
        IdLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        IdLbl.setText("ID:");
        IdLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        IdInput.setBackground(new java.awt.Color(238, 238, 238));
        IdInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        IdInput.setForeground(new java.awt.Color(51, 51, 51));
        IdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdInputActionPerformed(evt);
            }
        });

        AgeLbl.setBackground(new java.awt.Color(255, 255, 255));
        AgeLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        AgeLbl.setText("Age:");
        AgeLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        AgeInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        AgeInput.setModel(new javax.swing.SpinnerNumberModel(22, 18, 62, 1));

        GenderLbl.setBackground(new java.awt.Color(255, 255, 255));
        GenderLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        GenderLbl.setText("Gender:");
        GenderLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ContactLbl.setBackground(new java.awt.Color(255, 255, 255));
        ContactLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        ContactLbl.setText("Contact:");
        ContactLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ContactInput.setBackground(new java.awt.Color(238, 238, 238));
        ContactInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactInput.setForeground(new java.awt.Color(51, 51, 51));
        ContactInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactInputActionPerformed(evt);
            }
        });

        EmailLbl.setBackground(new java.awt.Color(255, 255, 255));
        EmailLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        EmailLbl.setText("Email:");
        EmailLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        EmailInput.setBackground(new java.awt.Color(238, 238, 238));
        EmailInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        EmailInput.setForeground(new java.awt.Color(51, 51, 51));
        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });

        CommunityLbl.setBackground(new java.awt.Color(255, 255, 255));
        CommunityLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        CommunityLbl.setText("Community:");
        CommunityLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        CommunityInput.setBackground(new java.awt.Color(238, 238, 238));
        CommunityInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CommunityInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Community" }));
        CommunityInput.setPreferredSize(new java.awt.Dimension(64, 23));
        CommunityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityInputActionPerformed(evt);
            }
        });

        CityLbl.setBackground(new java.awt.Color(255, 255, 255));
        CityLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CityLbl.setText("City:");
        CityLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        CityInput.setBackground(new java.awt.Color(238, 238, 238));
        CityInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CityInput.setForeground(new java.awt.Color(51, 51, 51));
        CityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityInputActionPerformed(evt);
            }
        });

        HouseNoLbl.setBackground(new java.awt.Color(255, 255, 255));
        HouseNoLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        HouseNoLbl.setText("House No:");
        HouseNoLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        HouseNoInput.setBackground(new java.awt.Color(238, 238, 238));
        HouseNoInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        HouseNoInput.setForeground(new java.awt.Color(51, 51, 51));
        HouseNoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseNoInputActionPerformed(evt);
            }
        });

        StreetLbl.setBackground(new java.awt.Color(255, 255, 255));
        StreetLbl.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        StreetLbl.setText("Street:");
        StreetLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        StreetInput.setBackground(new java.awt.Color(238, 238, 238));
        StreetInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        StreetInput.setForeground(new java.awt.Color(51, 51, 51));
        StreetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetInputActionPerformed(evt);
            }
        });

        GenderInput.setBackground(new java.awt.Color(238, 238, 238));
        GenderInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        GenderInput.setForeground(new java.awt.Color(51, 51, 51));
        GenderInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLbl)
                    .addComponent(IdLbl)
                    .addComponent(GenderLbl)
                    .addComponent(ContactLbl)
                    .addComponent(CommunityLbl)
                    .addComponent(CityLbl)
                    .addComponent(StreetLbl)
                    .addComponent(EmailLbl))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(AgeLbl)
                        .addGap(10, 10, 10)
                        .addComponent(AgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CommunityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(HouseNoLbl)
                        .addGap(10, 10, 10)
                        .addComponent(HouseNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ContactInput)
                    .addComponent(StreetInput)
                    .addComponent(EmailInput)
                    .addComponent(NameInput)
                    .addComponent(GenderInput))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLbl)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLbl)
                    .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeLbl)
                    .addComponent(AgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLbl)
                    .addComponent(GenderInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactLbl)
                    .addComponent(ContactInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLbl)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommunityLbl)
                    .addComponent(CommunityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLbl)
                    .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HouseNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HouseNoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetLbl)
                    .addComponent(StreetInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(469, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void IdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdInputActionPerformed

    private void ContactInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactInputActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void CommunityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityInputActionPerformed

    private void CityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityInputActionPerformed

    private void HouseNoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseNoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HouseNoInputActionPerformed

    private void StreetInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetInputActionPerformed

    private void GenderInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AgeInput;
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JTextField CityInput;
    private javax.swing.JLabel CityLbl;
    private javax.swing.JComboBox<String> CommunityInput;
    private javax.swing.JLabel CommunityLbl;
    private javax.swing.JTextField ContactInput;
    private javax.swing.JLabel ContactLbl;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JTextField GenderInput;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JTextField HouseNoInput;
    private javax.swing.JLabel HouseNoLbl;
    private javax.swing.JTextField IdInput;
    private javax.swing.JLabel IdLbl;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField StreetInput;
    private javax.swing.JLabel StreetLbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 private void addCommuniy() {
        String filePath = "/Users/vishwashah/Downloads/Assignment2/files/Community.csv";
       
        try (Scanner sc = new Scanner(new File(filePath))) {
            sc.useDelimiter("[,\n]");
            String[] temp = new String[3];
            while (sc.hasNext()) {
                for(int i = 0; i < temp.length; i++) {
                    temp[i] = sc.next();
                }
                CommunityInput.addItem(temp[1]);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonDirectory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void viewProfile() {
        String userEmail = LogIn.Instance.tmpLogInUsernameInput.getText();
        
        for(Person p:person.getPerson()) {
            String temp = p.getPersonEmail();
            if(temp.equals(userEmail)) {
                NameInput.setText(p.getPersonName());
                IdInput.setText(String.valueOf(p.getPersonID()));
                GenderInput.setText(p.getPersonGender());
                AgeInput.setValue(p.getPersonAge());
                ContactInput.setText(String.valueOf(p.getPersonContact()));
                EmailInput.setText(p.getPersonEmail());
                CommunityInput.setSelectedItem(p.getCommunity());
                CityInput.setText(p.getCity());
                HouseNoInput.setText(String.valueOf(p.getHouseNo()));
                StreetInput.setText(p.getStreet());
                
                NameInput.setEnabled(false);
                IdInput.setEnabled(false);
                GenderInput.setEnabled(false);
                AgeInput.setEnabled(false);
                ContactInput.setEnabled(false);
                EmailInput.setEnabled(false);
                CommunityInput.setEnabled(false);
                CityInput.setEnabled(false);
                HouseNoInput.setEnabled(false);
                StreetInput.setEnabled(false);
                
            }
        }
    }
}
